package io.graphcrud.model;

public enum NodeKind {
    INVOCATION_SOURCE,
    INVOCATION_BINDING,
    HTTP_ENDPOINT_BINDING,
    CONFIGURATION_ENTRY,
    JAVA_TYPE,
    UI_ACTION,
    SOURCE_FILE,
    CODE_SYMBOL,
    SQL_STATEMENT,
    TABLE
}
